name: Synopsys

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      POLARIS_SERVER_URL: ${{ secrets.POLARIS_SERVER_URL }} 
      POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}

    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Polaris
      run: | 
          curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
          unzip -d /tmp -jo polaris_cli-linux64.zip
          /tmp/polaris analyze -w
